import Link from "next/link";
import { notFound } from "next/navigation";
import AppShell from "@/components/app-shell";
import { requireAdmin } from "@/lib/auth";
import { supabaseServer } from "@/lib/supabase";
import { Panel, Table, Badge, Empty } from "@/components/ui";
import ResetPinButton from "./reset-pin-button";
import SupervisorManager from "./supervisor-manager";
import CodeSelector from "./code-selector";

const TYPE_LABEL: Record<string, string> = {
  salaried: "Salaried",
  full_time_hourly: "Full-time hourly",
  part_time: "Part-time",
  on_call: "On-call",
  seasonal: "Seasonal",
};

export default async function EmployeeDetail({ params }: { params: { id: string } }) {
  await requireAdmin();
  const sb = supabaseServer();

  const { data: employee } = await sb
    .from("employee_current")
    .select("*")
    .eq("id", params.id)
    .single();

  if (!employee) notFound();

  const [
    { data: assignments },
    { data: periods },
    { data: supervisors },
    { data: allEmployees },
    { data: workCodes },
    { data: myWorkCodes },
    { data: timeOffCodes },
    { data: myTimeOffCodes },
  ] = await Promise.all([
    sb.from("employee_assignments")
      .select("*, work_schedules(code), work_codes(code)")
      .eq("employee_id", params.id)
      .order("effective_from", { ascending: false }),
    sb.from("employment_periods")
      .select("*")
      .eq("employee_id", params.id)
      .order("hire_date", { ascending: false }),
    sb.from("supervisor_assignments")
      .select("supervisor_id, employees!supervisor_assignments_supervisor_id_fkey(id, first_name, last_name, employee_number)")
      .eq("employee_id", params.id),
    sb.from("employees")
      .select("id, first_name, last_name, employee_number")
      .eq("active", true)
      .order("last_name"),
    sb.from("work_codes").select("id, code, description").eq("active", true).order("code"),
    sb.from("employee_work_codes").select("work_code_id").eq("employee_id", params.id),
    sb.from("time_off_codes").select("id, code, description").eq("active", true).order("sort_order"),
    sb.from("employee_time_off_codes").select("time_off_code_id").eq("employee_id", params.id),
  ]);

  return (
    <AppShell>
      <div className="space-y-6">
        <div>
          <Link href="/admin/employees" className="text-sm text-[var(--accent)] hover:underline">
            ← All employees
          </Link>
          <h1 className="mt-2 text-xl font-semibold">
            {employee.first_name} {employee.last_name}
          </h1>
          <p className="mt-1 text-sm text-[var(--muted)]">
            #{employee.employee_number}
            {employee.original_hire_date && ` · original hire ${employee.original_hire_date}`}
          </p>
        </div>

        <Panel
          title="Login"
          description="PINs are generated by the system and cannot be retrieved — only reset."
        >
          <ResetPinButton employeeId={employee.id} />
        </Panel>

        <Panel
          title="Assignment history"
          description="Payroll type, employee type, and schedule are effective-dated. A change opens a new row."
        >
          <Table
            head={
              <>
                <th className="py-2 pr-4 font-medium">Effective</th>
                <th className="py-2 pr-4 font-medium">Payroll</th>
                <th className="py-2 pr-4 font-medium">Type</th>
                <th className="py-2 pr-4 font-medium">Schedule</th>
                <th className="py-2 pr-4 font-medium">Default code</th>
                <th className="py-2 font-medium">Holiday</th>
              </>
            }
          >
            {assignments?.map((a: any) => (
              <tr key={a.id} className="border-b border-[var(--line)] last:border-0">
                <td className="py-3 pr-4">
                  {a.effective_from} → {a.effective_to ?? "current"}
                </td>
                <td className="py-3 pr-4">
                  {a.payroll_type === "semi_monthly" ? "Semi-monthly" : "Bi-weekly"}
                </td>
                <td className="py-3 pr-4">{TYPE_LABEL[a.employee_type]}</td>
                <td className="py-3 pr-4">{a.work_schedules?.code}</td>
                <td className="py-3 pr-4 font-mono text-xs">{a.work_codes?.code ?? "—"}</td>
                <td className="py-3">
                  {a.holiday_eligible ? <Badge tone="good">Yes</Badge> : <Badge>No</Badge>}
                </td>
              </tr>
            ))}
          </Table>
        </Panel>

        <Panel
          title="Employment history"
          description="Seasonal rehires create a new period. Original hire date is the earliest."
        >
          {!periods?.length ? (
            <Empty>No employment periods.</Empty>
          ) : (
            <Table
              head={
                <>
                  <th className="py-2 pr-4 font-medium">Hired</th>
                  <th className="py-2 pr-4 font-medium">Terminated</th>
                  <th className="py-2 font-medium">Reason</th>
                </>
              }
            >
              {periods.map((p: any) => (
                <tr key={p.id} className="border-b border-[var(--line)] last:border-0">
                  <td className="py-3 pr-4">{p.hire_date}</td>
                  <td className="py-3 pr-4">
                    {p.term_date ?? <Badge tone="good">Active</Badge>}
                  </td>
                  <td className="py-3">{p.term_reason ?? "—"}</td>
                </tr>
              ))}
            </Table>
          )}
        </Panel>

        <SupervisorManager
          employeeId={employee.id}
          current={(supervisors ?? []).map((s: any) => ({
            id: s.employees.id,
            name: `${s.employees.first_name} ${s.employees.last_name}`,
            number: s.employees.employee_number,
          }))}
          candidates={(allEmployees ?? [])
            .filter((e: any) => e.id !== employee.id)
            .map((e: any) => ({
              id: e.id,
              name: `${e.first_name} ${e.last_name}`,
              number: e.employee_number,
            }))}
        />

        <CodeSelector
          employeeId={employee.id}
          workCodes={workCodes ?? []}
          selectedWorkCodes={(myWorkCodes ?? []).map((r: any) => r.work_code_id)}
          timeOffCodes={timeOffCodes ?? []}
          selectedTimeOffCodes={(myTimeOffCodes ?? []).map((r: any) => r.time_off_code_id)}
        />
      </div>
    </AppShell>
  );
}
