import Link from "next/link";
import { notFound } from "next/navigation";
import AppShell from "@/components/app-shell";
import { requireAdmin } from "@/lib/auth";
import { supabaseServer } from "@/lib/supabase";
import { Panel } from "@/components/ui";
import ResetPinButton from "./reset-pin-button";
import EmployeeFlags from "./employee-flags";
import AccrualRates from "./accrual-rates";
import AssignmentHistory from "./assignment-history";
import EmploymentHistory from "./employment-history";
import SupervisorManager from "./supervisor-manager";
import CodeSelector from "./code-selector";

const TYPE_LABEL: Record<string, string> = {
  salaried: "Salaried",
  full_time_hourly: "Full-time hourly",
  part_time: "Part-time",
  on_call: "On-call",
  seasonal: "Seasonal",
};

export default async function EmployeeDetail({ params }: { params: { id: string } }) {
  await requireAdmin();
  const sb = supabaseServer();

  const [
    { data: assignments },
    { data: employment },
    { data: allWorkCodes },
    { data: allSchedules },
  ] =
    await Promise.all([
      sb.rpc("assignment_history", { p_employee_id: params.id }),
      sb.rpc("employment_history", { p_employee_id: params.id }),
      sb.from("work_codes").select("*").eq("active", true).order("code"),
      sb.from("work_schedules").select("code, name").eq("active", true).order("code"),
    ]);

  // next period start, as the default effective date for a change
  const { data: nextPeriod } = await sb
    .from("pay_periods")
    .select("start_date")
    .gt("start_date", new Date().toISOString().slice(0, 10))
    .order("start_date", { ascending: true })
    .limit(1)
    .maybeSingle();

  const { data: rates } = await sb
    .from("accrual_rates")
    .select("*")
    .eq("employee_id", params.id)
    .order("effective_from", { ascending: false });

  const { data: employee } = await sb
    .from("employee_current")
    .select("*")
    .eq("id", params.id)
    .single();

  if (!employee) notFound();

  const [
    { data: supervisors },
    { data: allEmployees },
    { data: workCodes },
    { data: myWorkCodes },
    { data: timeOffCodes },
    { data: myTimeOffCodes },
  ] = await Promise.all([
    sb.from("supervisor_assignments")
      .select("supervisor_id, employees!supervisor_assignments_supervisor_id_fkey(id, first_name, last_name, employee_number)")
      .eq("employee_id", params.id),
    sb.from("employees")
      .select("id, first_name, last_name, employee_number")
      .eq("active", true)
      .order("last_name"),
    sb.from("work_codes").select("id, code, description").eq("active", true).order("code"),
    sb.from("employee_work_codes").select("work_code_id").eq("employee_id", params.id),
    sb.from("time_off_codes").select("id, code, description").eq("active", true).order("sort_order"),
    sb.from("employee_time_off_codes").select("time_off_code_id").eq("employee_id", params.id),
  ]);

  return (
    <AppShell>
      <div className="space-y-6">
        <div>
          <Link href="/admin/employees" className="text-sm text-[var(--accent)] hover:underline">
            ← All employees
          </Link>
          <h1 className="mt-2 text-xl font-semibold">
            {employee.first_name} {employee.last_name}
          </h1>
          <p className="mt-1 text-sm text-[var(--muted)]">
            #{employee.employee_number}
            {employee.original_hire_date && ` · original hire ${employee.original_hire_date}`}
          </p>
        </div>

        <EmployeeFlags employee={employee} />

        <AccrualRates employeeId={employee.id} rates={rates ?? []} />

        <AssignmentHistory
          employeeId={employee.id}
          assignments={assignments ?? []}
          workCodes={allWorkCodes ?? []}
          schedules={allSchedules ?? []}
          nextPeriodStart={
            nextPeriod?.start_date ?? new Date().toISOString().slice(0, 10)
          }
        />

        <EmploymentHistory
          employeeId={employee.id}
          periods={employment ?? []}
          active={employee.active}
          schedules={allSchedules ?? []}
          workCodes={allWorkCodes ?? []}
        />

        <Panel
          title="Login"
          description="PINs are generated by the system and cannot be retrieved — only reset."
        >
          <ResetPinButton employeeId={employee.id} />
        </Panel>


        <SupervisorManager
          employeeId={employee.id}
          current={(supervisors ?? []).map((s: any) => ({
            id: s.employees.id,
            name: `${s.employees.first_name} ${s.employees.last_name}`,
            number: s.employees.employee_number,
          }))}
          candidates={(allEmployees ?? [])
            .filter((e: any) => e.id !== employee.id)
            .map((e: any) => ({
              id: e.id,
              name: `${e.first_name} ${e.last_name}`,
              number: e.employee_number,
            }))}
        />

        <CodeSelector
          employeeId={employee.id}
          workCodes={workCodes ?? []}
          selectedWorkCodes={(myWorkCodes ?? []).map((r: any) => r.work_code_id)}
          timeOffCodes={timeOffCodes ?? []}
          selectedTimeOffCodes={(myTimeOffCodes ?? []).map((r: any) => r.time_off_code_id)}
        />
      </div>
    </AppShell>
  );
}
